# Generated by Django 2.1.5 on 2019-03-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='mail',
            field=models.CharField(default='abc@123.gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
