# Generated by Django 2.1.5 on 2019-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='mail',
        ),
    ]
